### ISSUE TITLE
Using the value 0 in the cache

### ISSUE THREAD

**Issue by filipebraida** [Melchyore/adonis-cache#2]
## Description

Firstly, your package is very useful and I use it in one of my projects. Besides using it as a cache, I also use it to share application configuration variables between processes. In one case, I need to save a threshold that varies between [0.0, 1.0] and I use the `rememberForever` function. One possibility is to set it to 0. At this point, the library performs a validation if it returned any value from the repository and executes the closure. 

Wouldn't it be more appropriate to check if it returns null or undefined? 

One way to work around the problem is to cast the number to a string.

## Package version
@melchyore/adonis-cache: "^1.0.4"

## Error Message & Stack Trace
Not applicable in this case.

## Relevant Information
I am using the Postgres database as a cache.

Link:
https://github.com/Melchyore/adonis-cache/blob/45caff79c7778728dddc33a293ebd1ae02ccef19/src/Repository.ts#LL261C1-L264C1

**Comment by Melchyore** [comment]
@filipebraida Hey 👋

I will look into this bug, thank you for reporting.

**Comment by Melchyore** [comment]
@filipebraida Please upgrade to v1.0.5.

**Comment by filipebraida** [comment]
Thanks @Melchyore !

**Comment by Melchyore** [comment]
> Thanks @Melchyore !

Welcome!
